---

- name: install
  shell: >
    wget "https://api.equinox.io/1/Applications/ap_pJSFC5wQYkAyI0FIVwKYs9h1hW/Updates/Asset/ngrok.zip?os=linux&arch=amd64&channel=stable" -O /tmp/ngrok.zip && unzip -o /tmp/ngrok.zip -d /usr/local/bin && rm /tmp/ngrok.zip
    creates=/usr/local/bin/ngrok
  sudo: yes
